name: happypass
description: a highly liberal http framework! In happypass, you can contorl all of the request process, and re-design anything you need.
version: 1.1.3
homepage: https://github.com/CimZzz/happypass

environment:
  sdk: '>=2.2.0 <3.0.0'
